version: "3.9"
services:
  web:
    build: ./flask
    ports:
      - "5000:5000"
    volumes:
      - ./flask:/code
    environment:
      FLASK_ENV: development
  redis:
    image: "redis:alpine"
  db_sqlite:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./db/:/code/
